apiVersion: v2
name: hybridnet
# When the version is modified, make sure the artifacthub.io/changes list is updated
# Also update CHANGELOG.md
version: 0.2.1
appVersion: 0.4.3
home: https://github.com/alibaba/hybridnet
description: A container networking solution aiming at hybrid clouds.
keywords:
  - network
  - vlan
  - bgp
  - vxlan
  - cni
  - kubernetes
sources:
  - https://github.com/alibaba/hybridnet
type: application
kubeVersion: ">=1.16.0-0"
annotations:
  # Use this annotation to indicate that this chart version is a pre-release.
  artifacthub.io/prerelease: "false"
  # List of changes for the release in artifacthub.io
  artifacthub.io/changes: |
    - "introduce flag for daemon to enable/disable enhanced addresses"
    - "introduce environment variable on DualStack mode to specify defualt ip family"
    - "skip webhook validation on hostnetwork pods"
    - "introduce flag for daemon to help select vtep address"
    - "fix daemon policy container init error on nodes with only ipv6 addresses"
    - "node annotation changed should trigger the reconcile of daemon Node controller"
    - "fix route table 40000 used by others error of daemon which happens if an ipv6 subnet with excluded ip ranges is created"
    - "fix daemon updating IPInstance status error while a pod has multiple ip instances"
    - "fix the error that arp enhanced addresses will be taken as source ip address by mistake"
    - "fix the error that deprecated bgp rules and routes are not cleaned"
    - "fix chart's typo error"
