apiVersion: v2
name: hybridnet
# When the version is modified, make sure the artifacthub.io/changes list is updated
# Also update CHANGELOG.md
version: 0.2.2
appVersion: 0.4.4
home: https://github.com/alibaba/hybridnet
description: A container networking solution aiming at hybrid clouds.
keywords:
  - network
  - vlan
  - bgp
  - vxlan
  - cni
  - kubernetes
sources:
  - https://github.com/alibaba/hybridnet
type: application
kubeVersion: ">=1.16.0-0"
annotations:
  # Use this annotation to indicate that this chart version is a pre-release.
  artifacthub.io/prerelease: "false"
  # List of changes for the release in artifacthub.io
  artifacthub.io/changes: |
    - "fix the error that nodes get "empty" quota while the Underlay Network still have available addresses to allocate"
    - "fix daemon policy container exit with ip6tables-legacy-save error"
